services:
  discord-bot:
    build: .
    container_name: discord_bot
    restart: always
    env_file:
      - .env
    environment:
      - MUSIC_PATH=/usr/src/app/Musique
    volumes:
      - ${HOME}/Music/1-TelechargesViaDiscord:/usr/src/app/Musique
      - ./ytbChannels:/usr/src/app/ytbChannels
